version: 2
jobs:
  build:
    working_directory: ~/ansible-test-runner
    docker:
      - image: circleci/python:3.7
    steps:
      - restore_cache:
          keys:
          - deps-{{ .Branch }}-{{ .Revision }}
          - deps-{{ .Branch }}
          - deps-
      - checkout
      - run: |
          python3.7 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - save_cache:
          keys:
          - deps-{{ .Branch }}-{{ .Revision }}
          - deps-{{ .Branch }}
          - deps-
          paths:
          - "venv"
      - run:
          command: venv/bin/python -m xmlrunner -o ../test-results/functional_test
          working_directory: ~/ansible-test-runner/functional_test
      - store_test_results:
          path: test-results