version: 2
jobs:
  build:
    working_directory: ~/ansible-test-runner
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout

      - restore_cache:
          keys:
          - deps-{{ checksum "requirements.txt" }}
          - deps-

      - run: |
          python3.7 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - save_cache:
          key: deps-{{ checksum "requirements.txt" }}
          paths:
          - "./venv"

      - run:
          working_directory: ~/ansible-test-runner/functional_test
          command: |
            source ../venv/bin/activate
            python -m xmlrunner -o ../test-results/functional_test

      - store_test_results:
          path: test-results